version: "3"
services:
  database:
    container_name: event-db
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: event-app-user
      MYSQL_DATABASE: event-app-db
      MYSQL_USER: event-app-user
      MYSQL_PASSWORD: event-app-user
  server:
    build: ./server
    ports:
      - "5000:5000"
    # volumes:
    #   - ./static:/go/src/temp/static
    #   - ./views:/go/src/temp/views
    # command: bash -c 'cd /go/src/temp && go run main.go'
    restart: always
    depends_on:
      - "database"
