version: "3"
services:
  database:
    container_name: event-db
    image: mysql
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: event-app-user
      MYSQL_DATABASE: event-app-db
      MYSQL_USER: event-app-user
      MYSQL_PASSWORD: event-app-user
  server:
    container_name: event-server
    build: ./server
    restart: always
    depends_on:
      - "database"
  client:
    build: ./client
    depends_on:
      - "server"
  nginx:
    build: ./client/nginx
    ports:
      - 80:80
    depends_on:
      - "client"
