version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: event-app-user
      MYSQL_DATABASE: event-app-db
      MYSQL_USER: event-app-user
      MYSQL_PASSWORD: event-app-user
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # volumes:
    #   - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
  dbdata:
